INSERT INTO users (name, age) VALUES ("Jessie", 26);
INSERT INTO users (name, age) VALUES ("Nolan", 26);
INSERT INTO users (name, age) VALUES ("Zane", 26);
INSERT INTO users (name, age) VALUES ("Traci", 27);
INSERT INTO users (name, age) VALUES ("Sandy", 27);
INSERT INTO users (name, age) VALUES ("Jonny", 26);
INSERT INTO users (name, age) VALUES ("Rachael", 26);
INSERT INTO users (name, age) VALUES ("Mark", 26);
INSERT INTO users (name, age) VALUES ("Dave", 58);
INSERT INTO users (name, age) VALUES ("Diana", 58);
INSERT INTO users (name, age) VALUES ("Patty", 60);
INSERT INTO users (name, age) VALUES ("Bob", 57);
INSERT INTO users (name, age) VALUES ("Danny", 30);
INSERT INTO users (name, age) VALUES ("Jacqui", 29);
INSERT INTO users (name, age) VALUES ("Bianca", 26);
INSERT INTO users (name, age) VALUES ("Adam L", 28);
INSERT INTO users (name, age) VALUES ("Adam S", 27);
INSERT INTO users (name, age) VALUES ("Adam H", 27);
INSERT INTO users (name, age) VALUES ("Brandon", 26);
INSERT INTO users (name, age) VALUES ("Braton", 29);
